apiVersion: v1
entries:
  metal-community-service:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-22T20:40:00.584617821Z"
    description: A Helm chart for the metal community service
    digest: a1fca042753a8c6632c5292fb14692e6681ea848a39ecef00f9cd08836d38731
    name: metal-community-service
    type: application
    urls:
    - https://azapatamoli.github.io/metal-community-service/charts/metal-community-service-0.1.0.tgz
    version: 0.1.0
generated: "2025-04-22T20:40:00.584095714Z"
