name: Release Chart
on:
  push:
    branches: ["main"]
    paths:
      - "metal-community-service/**"
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        id: install
      - name: Package Helm chart
        run: |
          mkdir -p /tmp/charts
          helm package ./metal-community-service --destination /tmp/charts
      - name: Checkout gh-pages branch
        run: |
          git config --global user.email "zapatamolinaalejandro@gmail.com"
          git config --global user.name "Alejandro Zapata"
          git fetch origin gh-pages
          git switch gh-pages
          rm -f *.tgz || true
          cp /tmp/charts/*.tgz ./
      - name: Generate index.yaml
        run: |
          helm repo index . --url https://alejandro2134.github.io/metal-community-manifests --merge index.yaml
      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Helm chart"
          git push origin gh-pages
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
