name: Release Chart
on:
  push:
    branches: ["main"]
    paths:
      - "metal-community-service/**"
permissions:
  contents: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        id: install
      - name: Package Helm chart
        run: |
          helm package ./metal-community-service --destination chart-packages
      - name: Checkout gh-pages branch
        run: |
          git config --global user.email "azapatamoli@gmail.com"
          git config --global user.name "Alejandro Zapata"
          git fetch origin gh-pages
          git switch gh-pages
          mkdir -p charts
          mv chart-packages/*.tgz charts/
      - name: Generate index.yaml
        run: |
          helm repo index charts --url https://azapatamoli.github.io/metal-community-service/charts
      - name: Commit and push changes
        run: |
          git add charts
          git commit -m "Update Helm chart"
          git push origin gh-pages
